### ISSUE TITLE
Adding rustfmt to pre-commit-hooks

### ISSUE THREAD

**Issue by szg251** [mlabs-haskell/lambda-buffers#109]
By default, `rustfmt` looks for a `Cargo.toml` file in the root directory to determines which files should be formatted. However, as we're using a monorepo structure there's no such file, so the pre-commit-hook fails. We must find a way to tell `rustfmt` where the package roots are.
Previously I configured cargo workspaces, which solved the problem, but it is not in alignment with the rules of our monorepo (the repo should be language agnostic), so this is a no-go.

**Comment by bladyjoker** [comment]
Thank you for opening this issue. 

I looked into https://github.com/cachix/pre-commit-hooks.nix/blob/master/modules/hooks.nix and found that there's a Rust wide option to set the location of the Cargo manifest file (I think that's it right?).

Both rustfmt and clippy are using this.

That being said, can we add clippy as well?

**Comment by szg251** [comment]
Ok, this was easy... 
I will add both

**Comment by szg251** [comment]
I found a problem, this only allows configuring one manifest file, but we will have multiple ones eventually...
I guess we will need to request a new feature, or implement it ourselves.

**Comment by bladyjoker** [comment]
Legitimate problem that's making monorepos more difficult. Hmmm...

**Comment by bladyjoker** [comment]
Stupid question! What's the content of said Manifest? Is it something generic? If so, we can just have it provided as a derivation :)

**Comment by szg251** [comment]
It's basically the same as a `xyz.cabal` file in Haskell. I wouldn't go in that direction.
I think we could define a custom hook, at least as a temporary solution..

**Comment by szg251** [comment]
Maybe we could trick the system by providing a workspace root manifest file as derivation...
I'll give this a go
