### ISSUE TITLE
Create a Rust Plutus runtime library

### ISSUE THREAD

**Issue by szg251** [mlabs-haskell/lambda-buffers#111]
Create a prelude module for Plutus specific functions in Rust.
There are two options to be used as the supporting libraries: `cardano-serialisation-lib` or `pallas-primitives`.

- [x] research and decide which of the above two libraries to use
- [ ] implement and test

**Comment by bladyjoker** [comment]
TODO:
- Implement the Rust plutus-ledger-api lib
- Separate repo
- Use Cargo feature flag feature to disable/enable lambdabuffers dependency (i guess that's lbr-prelude/plutus)
- Implement Json and PlutusData encodings for the opaque types

**Comment by szg251** [comment]
Issue is now tracked through these PRs:
https://github.com/mlabs-haskell/lambda-buffers/pull/118
https://github.com/mlabs-haskell/plutus-ledger-types-rust/pull/1
